/* eslint-disable max-len */
import makeStyles from '@material-ui/core/styles/makeStyles';
import {
    BLUE_GRAY, GRAY_THIRD, ORANGE, WHITE, TEXT_SHADE, BLUE_PRIMARY, BLACK_GRAY, BLACK_DARK,
} from '@theme_color';

export default makeStyles((theme) => ({
    container: {
        width: '100%',
        height: '100%',
    },
    wrapperSkeleton: {
        maxWidth: '800px',
        width: '100%',
        display: 'flex',
        flexWrap: 'wrap',
        paddingLeft: 0,
        paddingRight: 0,
        paddingTop: 0,
        [theme.breakpoints.up('lg')]: {
            margin: 0,
        },
        '& > li': {
            width: '50%',
            padding: 8,
            [theme.breakpoints.down('md')]: {
                width: '50%',
            },
            [theme.breakpoints.down('sm')]: {
                width: '100%',
            },
            '& .MuiSkeleton-root': {
                paddingBottom: '30%',
                width: '100%',
                borderRadius: 15,
            },
        },
    },
    containerButton: {
        textAlign: 'right',
        marginBottom: 20,
        marginTop: 20,
    },
    buttonBack: {
        height: 40,
        padding: '0 !important',
        borderRadius: 20,
        textAlign: 'center!important',
        fontSize: 14,
        border: '0 transparent!important',
        fontWeight: 400,
        textDecoration: 'none',
        margin: 0,
        background: 'none !important',
        color: '#f58732!important',
        textTransform: 'capitalize!important',
        alignSelf: 'left',
        justifyContent: 'flex-start',
        '&:hover': {
            height: 40,
            padding: '0 !important',
            borderRadius: 20,
            textAlign: 'center!important',
            fontSize: 14,
            border: '0 transparent!important',
            fontWeight: 400,
            textDecoration: 'none!important',
            margin: 0,
            background: 'none !important',
        },
    },
    subjectTicket: {
        fontWeight: 400,
        color: TEXT_SHADE,
        fontSize: 30,
        letterSpacing: 0.28,
    },
    subjectTicketSub: {
        fontWeight: 400,
        marginTop: 20,
        marginBottom: 32,
        color: TEXT_SHADE,
        '& span': {
            marginLeft: 78,
            letterSpacing: 0.28,
            [theme.breakpoints.down('xs')]: {
                marginLeft: 20,
            },
        },
    },
    topPanel: {
        borderRadius: 8,
        backgroundColor: '#f2f9ff',
        justifyContent: 'space-between',
        display: 'flex',
        flexWrap: 'wrap',
        padding: '20px 15px',
        marginBottom: 8,
        '& h5': {
            color: TEXT_SHADE,
        },
        '& .MuiRating-root': {
            '& .MuiRating-iconEmpty': {
                color: BLUE_PRIMARY,
            },
        },
        [theme.breakpoints.down('xs')]: {
            display: 'grid',
            gap: 20,
        },
    },
    contentPanel: {
        display: 'flex',
        justifyContent: 'center',
        gap: '16px',
        [theme.breakpoints.down('348')]: {
            flexDirection: 'column',
            gap: '4px',
        },
    },
    titleElement: {
        fontWeight: 'bold',
        marginBottom: 5,
        display: 'block',
        fontSize: 14,
        '& .required': {
            color: '#e02b27',
        },
    },
    valueElement: {
        fontWeight: 400,
        marginBottom: 5,
        display: 'block',
        fontSize: 14,
    },
    buttonEscalate: {
        background: 'none',
        color: ORANGE,
        fontWeight: 400,
        width: 'max-content',
        height: 40,
        borderRadius: 50,
        border: `1px solid ${ORANGE}`,
        padding: '0 20px!important',
        textTransform: 'capitalize!important',
        '&:hover': {
            background: 'none',
            color: ORANGE,
            fontWeight: 400,
            height: 40,
            borderRadius: 50,
            border: `1px solid ${ORANGE}`,
            padding: '0 20px!important',
            textTransform: 'capitalize!important',
        },
    },
    containerMessage: {
        display: 'flex',
        justifyContent: 'center',
    },
    success: {
        width: '100%',
        maxWidth: '1280px',
        margin: '10px 0 0 0',
        padding: '12px 20px 12px 25px',
        display: 'block',
        fontSize: '14px',
        background: '#e5efe5',
        color: '#006400',
        paddingLeft: '45px',
        position: 'relative',
        '&:first-child:before': {
            '-webkit-font-smoothing': 'antialiased',
            '-moz-osx-font-smoothing': 'grayscale',
            fontSize: '24px',
            lineHeight: '24px',
            color: '#006400',
            content: '\\e60e',
            fontFamily: 'luma-icons',
            margin: '-12px 0 0',
            verticalAlign: 'middle',
            display: 'inline-block',
            fontWeight: 'normal',
            overflow: 'hidden',
            speak: 'none',
            left: 0,
            top: '22px',
            width: '45px',
            position: 'absolute',
            textAlign: 'center',
        },
    },
    error: {
        width: '100%',
        maxWidth: '1280px',
        margin: '10px 0 0 0',
        padding: '12px 20px 12px 25px',
        display: 'block',
        fontSize: '14px',
        background: '#fae5e5',
        color: '#e02b27',
        paddingLeft: '45px',
        position: 'relative',
        '&:first-child:before': {
            '-webkit-font-smoothing': 'antialiased',
            '-moz-osx-font-smoothing': 'grayscale',
            fontSize: '24px',
            lineHeight: '24px',
            color: '#b30000',
            content: '\\e61f',
            fontFamily: 'luma-icons',
            margin: '-12px 0 0',
            verticalAlign: 'middle',
            display: 'inline-block',
            fontWeight: 'normal',
            overflow: 'hidden',
            speak: 'none',
            left: 0,
            top: '22px',
            width: '45px',
            position: 'absolute',
            textAlign: 'center',
        },
    },
    replyPanel: {
        borderRadius: 8,
        backgroundColor: '#f2f9ff',
        marginBottom: 16,
        padding: '20px',
        '& h5': {
            marginBottom: 7,
            textTransform: 'capitalize',
            color: TEXT_SHADE,
        },
    },
    closedPanel: {
        marginBottom: 5,
        display: 'block',
        fontSize: 14,
        fontWeight: 'bold',
        '& a': {
            color: ORANGE,
        },
    },
    inputArea: {
        background: '#ffffff',
        backgroundclip: 'padding-box',
        border: '1px solid #d5eafb',
        borderRadius: 5,
        fontSize: 14,
        height: 'auto',
        lineHeight: 1.42857143,
        margin: 0,
        padding: 10,
        verticalAlign: 'baseline',
        width: '100%',
        boxSizing: 'border-box',
        resize: 'vertical',
        '&:not([disabled]):focus': {
            boxShadow: '0 0 3px 1px #00699d',
        },
        '&:focus-visible': {
            outline: 0,
        },
    },
    inputFileContainer: {
        display: 'flex',
        justifyContent: 'space-between',
        marginTop: 5,
        marginBottom: 4,
        gap: 20,
        '& .file-uploader-frame': {
            paddingLeft: '0px !important',
        },
        '& .input-file-inner-container': {
            display: 'flex',
            alignItems: 'center',
            gap: '5px',
            '& .attach-icon': {
                color: GRAY_THIRD,
                fontSize: 21,
                transform: 'rotate(45deg)',
            },
            '& .file-uploader-button': {
                // backgroundImage: 'none',
                background: '0 0',
                '-moz-box-sizing': 'content-box',
                border: 0,
                boxShadow: 'none',
                cursor: 'pointer',
                lineHeight: 'inherit',
                margin: 0,
                padding: 0,
                textDecoration: 'none',
                textShadow: 'none',
                fontWeight: 500,
                color: '#f58732',
                fontSize: 13,
            },
        },
        '& .file-area': {
            cursor: 'pointer',
            opacity: 0,
            overflow: 'hidden',
            position: 'absolute',
            visibility: 'hidden',
            width: 0,
        },
    },
    attachInfo: {
        color: BLUE_GRAY,
    },
    actionBottom: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    buttonSend: {
        backgroundColor: '#f58732!important',
        color: '#FFFFFF!important',
        height: 40,
        padding: '0 25px!important',
        whiteSpace: 'nowrap',
        borderRadius: 20,
        textAlign: 'center',
        fontSize: 14,
        border: '0 transparent!important',
        fontWeight: 400,
        textTransform: 'capitalize!important',
        width: '100%',
        '&:hover': {
            backgroundColor: '#f58732!important',
            color: '#FFFFFF!important',
        },
    },
    buttonClose: {
        backgroundColor: ORANGE,
        color: WHITE,
        height: 40,
        padding: '0 25px!important',
        borderRadius: 20,
        textAlign: 'center',
        fontSize: 14,
        border: '0 transparent!important',
        fontWeight: 400,
        whiteSpace: 'nowrap',
        textTransform: 'capitalize!important',
        '&:hover': {
            backgroundColor: ORANGE,
            color: WHITE,
        },
    },
    itemMessage: {
        backgroundColor: '#d5eafb',
        border: '0 transparent',
        borderLeft: '3px solid #06aec9',
        padding: '25px 15px',
        marginBottom: 10,
        '& h4': {
            color: BLACK_GRAY,
            letterSpacing: 0.24,
        },
        '& h4:first-child': {
            color: BLACK_DARK,
        },
    },
    contentMessage: {
        width: '100%',
        marginTop: 10,
        fontSize: 14,
        border: 'none',
        lineHeight: 25,
        wordBreak: 'break-all',
        whiteSpace: 'pre-line',
        '& h3': {
            color: BLACK_GRAY,
            letterSpacing: 0.28,
        },
    },
    contentAttachment: {
        marginTop: 30,
        '& a': {
            display: 'flex',
            color: ORANGE,
            letterSpacing: 0.28,
            marginLeft: 5,
        },
        '& a:hover': {
            textDecoration: 'underline',
        },
    },
}));
