/* eslint-disable max-len */
import makeStyles from '@material-ui/core/styles/makeStyles';
import {
    BLUE_LIGHT, BLUE_PRIMARY, GRAY_THIRD, TEXT_SHADE, BLUE_GRAY,
} from '@theme_color';

export default makeStyles((theme) => ({
    pageTitles: {
        marginBottom: '20px',
        textTransform: 'uppercase',
    },
    container: {
        marginLeft: 'auto',
        marginRight: 'auto',
        maxWidth: '1280px',
        paddingLeft: '20px',
        paddingRight: '20px',
        paddingBottom: '40px',
    },
    contentWrapper: {
        margin: '20px 0',
        padding: '0 60px',
        display: 'flex',
        gap: '40px',
        flexDirection: 'row-reverse',
        '& .left-side': {
            width: '80%',
            paddingLeft: '40px',
            borderLeft: `solid ${BLUE_PRIMARY} 1px`,
            [theme.breakpoints.down('xs')]: {
                paddingLeft: '0 !important',
                borderLeft: '0 !important',
                borderTop: '1px solid #d5eafb',
                paddingTop: '30px',
                width: '100%',
            },
        },
        '& .right-side': {
            width: '100%',
        },
        '& .medbizcare-logo': {
            maxWidth: '300px',
            marginBottom: '10px',
        },
        '& .social-info': {
            width: '100%',
            borderCollapse: 'collapse',
            borderSpacing: 0,
            maxWidth: '100%',
        },
        '& .social-info tbody tr td:first-child span': {
            width: '20px',
            display: 'inline-table',
            textAlign: 'center',
        },
        '& .social-info tbody tr td:first-child': {
            paddingLeft: 0,
            width: '120px',
            fontWeight: 700,
        },
        '& .social-info tbody tr td': {
            padding: 8,
        },
        '& .social-info tbody tr td:last-child:before': {
            display: 'inline',
            content: ':',
            marginRight: '10px',
        },
        [theme.breakpoints.down('xs')]: {
            flexDirection: 'column-reverse !important',
            padding: '0 10px !important',
        },
    },
    containerForm: {
        '& .input-container': {
            marginBottom: 12,
            '& span': {
                margin: 0,
            },
            '& .input': {
                width: '100%',
                height: 40,
                padding: '10px',
                borderRadius: 5,
                border: `solid ${BLUE_GRAY} 1px`,
                outline: 'none',
                color: '#414048',
                fontSize: 14,
                background: '#fff',
                '& option': {
                    background: '#fff',
                },
            },
            '& .textarea': {
                height: 'unset',
                resize: 'vertical',
                border: `1px solid ${BLUE_PRIMARY}`,
                minHeight: 140,
            },
            '& div[class*="MuiAutocomplete-hasPopupIcon"]': {
                padding: '5px 10px 10px 10px',
                '& div[class*="MuiFormControl-root"]': {
                    '& div[class*="MuiAutocomplete-inputRoot"]': {
                        padding: '0px',
                    },
                },
            },
            '& #department_id': {
                WebkitAppearance: 'none',
                MozAppearance: 'none',
                background: 'url(/assets/img/arrow-dropdown.png) no-repeat calc(100% - 15px) 50%',
                backgroundSize: 12,
            },
            '& #order_id': {
                fontSize: 14,
                color: '#414048',
                padding: '7px 0 !important',
            },
        },
        '& .label': {
            display: 'block',
            fontWeight: 'bold',
            textAlign: 'left',
            marginBottom: 5,
            color: TEXT_SHADE,
            '& span': {
                textAlign: 'left',
                color: 'red !important',
                fontSize: 12,
            },
        },
    },
    inputRecipient: {
        marginBottom: 5,
    },
    buttonSubmit: {
        padding: '7px 16px !important',
        marginRight: '4px',
        borderRadius: '25px !important',
        border: 0,
        fontWeight: 'normal',
        background: '#f58732 !important',
        textTransform: 'none',
        '& span': {
            fontSize: 14,
            fontWeight: 400,
            letterSpacing: 0,
        },
    },
    note: {
        margin: '0 0 36px 0 !important',
        fontSize: '30px !important',
        color: TEXT_SHADE,
    },
    fullName: {
        border: '1px solid #d5eafb',
        minHeight: '40px',
    },
    btnSubmit: {
        marginTop: 50,
        textAlign: 'left',
    },
    message: {
        marginBottom: 30,
    },
    skeletonForm: {
        marginBottom: 20,
    },
    success: {
        margin: '0 0 10px',
        padding: '12px 20px 12px 25px',
        display: 'block',
        fontSize: '14px',
        background: '#e5efe5',
        color: '#006400',
        paddingLeft: '45px',
        position: 'relative',
        '&:first-child:before': {
            '-webkit-font-smoothing': 'antialiased',
            '-moz-osx-font-smoothing': 'grayscale',
            fontSize: '24px',
            lineHeight: '24px',
            color: '#006400',
            content: '\\e60e',
            fontFamily: 'luma-icons',
            margin: '-12px 0 0',
            verticalAlign: 'middle',
            display: 'inline-block',
            fontWeight: 'normal',
            overflow: 'hidden',
            speak: 'none',
            left: 0,
            top: '22px',
            width: '45px',
            position: 'absolute',
            textAlign: 'center',
        },
    },
    error: {
        margin: '0 0 10px',
        padding: '12px 20px 12px 25px',
        display: 'block',
        fontSize: '14px',
        background: '#fae5e5',
        color: '#e02b27',
        paddingLeft: '45px',
        position: 'relative',
        '&:first-child:before': {
            '-webkit-font-smoothing': 'antialiased',
            '-moz-osx-font-smoothing': 'grayscale',
            fontSize: '24px',
            lineHeight: '24px',
            color: '#b30000',
            content: '\\e61f',
            fontFamily: 'luma-icons',
            margin: '-12px 0 0',
            verticalAlign: 'middle',
            display: 'inline-block',
            fontWeight: 'normal',
            overflow: 'hidden',
            speak: 'none',
            left: 0,
            top: '22px',
            width: '45px',
            position: 'absolute',
            textAlign: 'center',
        },
    },
    inputFileContainer: {
        background: BLUE_LIGHT,
        padding: '12px 8px',
        '& .input-file-inner-container': {
            display: 'flex',
            alignItems: 'center',
            gap: '5px',
            '& .attach-icon': {
                color: GRAY_THIRD,
                fontSize: 21,
                transform: 'rotate(45deg)',
            },
            '& .file-uploader-button': {
                background: '0 0',
                '-moz-box-sizing': 'content-box',
                border: 0,
                boxShadow: 'none',
                cursor: 'pointer',
                lineHeight: 'inherit',
                margin: 0,
                padding: 0,
                textDecoration: 'none',
                textShadow: 'none',
                fontWeight: 500,
                color: '#f58732',
                fontSize: 13,
            },
            '& .file-area': {
                cursor: 'pointer',
                opacity: 0,
                overflow: 'hidden',
                position: 'absolute',
                visibility: 'hidden',
                width: 0,
            },
        },
    },
    recipientInfo: {
        margin: 0,
        color: BLUE_GRAY,
        fontSize: 12,
        letterSpacing: 0,
    },
    createTicketFooter: {
        display: 'flex',
        marginBottom: 20,
        flexDirection: 'row',
        '& > div': {
            width: 'auto',
        },
        '& .button-back ': {
            padding: '12px 21px',
            '& span': {
                fontSize: 14,
                color: '#f58732',
                margin: 0,
                fontWeight: '400',
            },
        },
    },
    maxAttachFiles: {
        color: '#7b9aaf',
        marginBottom: '30px',
        fontSize: '12px',
        width: 'auto',
        display: 'block',
    },
}));
